src/Entity/Usuario.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * Usuario
 *
 * @ORM\Table(name="usuario", indexes={@ORM\Index(name="fk_usuario_tipo_usuario1_idx", columns={"tipo_usuario_idtipo_usuario"})})
 * @ORM\Entity
 */
class Usuario implements UserInterface
{
    /**
     * @var int
     *
     * @ORM\Column(name="idusuario", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idusuario;

    /**
     * @var string
     *
     * @ORM\Column(name="login", type="string", length=45, nullable=false)
     */
    private $login;

    /**
     * @var string
     *
     * @ORM\Column(name="senha", type="string", length=255, nullable=false)
     */
    private $senha;

    /**
     * @var \TipoUsuario
     *
     * @ORM\ManyToOne(targetEntity="TipoUsuario")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="tipo_usuario_idtipo_usuario", referencedColumnName="idtipo_usuario")
     * })
     */
    private $tipoUsuarioIdtipoUsuario;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $roles;


    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="Estabelecimento", inversedBy="usuarioIdfuncionario")
     * @ORM\JoinTable(name="usuario_has_estabelecimento",
     *   joinColumns={
     *     @ORM\JoinColumn(name="usuario_idfuncionario", referencedColumnName="idusuario")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="estabelecimento_idestabelecimento", referencedColumnName="idestabelecimento")
     *   }
     * )
     */
    private $estabelecimentoIdestabelecimento;

    public function __toString()
    {
        return $this->login;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->estabelecimentoIdestabelecimento = new \Doctrine\Common\Collections\ArrayCollection();
    }

    public function getIdusuario(): ?int
    {
        return $this->idusuario;
    }

    public function getLogin(): ?string
    {
        return $this->login;
    }

    public function setLogin(string $login): self
    {
        $this->login = $login;

        return $this;
    }

    public function getSenha(): ?string
    {
        return $this->senha;
    }

    public function setSenha(string $senha): self
    {
        $this->senha = $senha;

        return $this;
    }

    public function getTipoUsuarioIdtipoUsuario(): ?TipoUsuario
    {
        return $this->tipoUsuarioIdtipoUsuario;
    }

    public function setTipoUsuarioIdtipoUsuario(?TipoUsuario $tipoUsuarioIdtipoUsuario): self
    {
        $this->tipoUsuarioIdtipoUsuario = $tipoUsuarioIdtipoUsuario;

        return $this;
    }

    /**
     * @return Collection|Estabelecimento[]
     */
    public function getEstabelecimentoIdestabelecimento(): Collection
    {
        return $this->estabelecimentoIdestabelecimento;
    }

    public function addEstabelecimentoIdestabelecimento(Estabelecimento $estabelecimentoIdestabelecimento): self
    {
        if (!$this->estabelecimentoIdestabelecimento->contains($estabelecimentoIdestabelecimento)) {
            $this->estabelecimentoIdestabelecimento[] = $estabelecimentoIdestabelecimento;
        }

        return $this;
    }

    public function removeEstabelecimentoIdestabelecimento(Estabelecimento $estabelecimentoIdestabelecimento): self
    {
        if ($this->estabelecimentoIdestabelecimento->contains($estabelecimentoIdestabelecimento)) {
            $this->estabelecimentoIdestabelecimento->removeElement($estabelecimentoIdestabelecimento);
        }

        return $this;
    }

    public function getRoles()
    {
        return !$this->roles ? [] : explode(',', $this->roles);
    }

    public function setRoles($roles):Usuario
    {
        $this->roles = implode(',' , $roles);
        return $this;
    }

    public function getPassword()
    {
        return $this->getSenha();
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function getUsername()
    {
        return $this->getLogin();
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
}

templates/admin.html.twig
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <title>Dashio - Bootstrap Admin Template</title>

    <!-- Favicons -->
    <link href="{{ asset('img/favicon.png') }}" rel="icon">
    <link href="{{ asset('img/apple-touch-icon.png') }}" rel="apple-touch-icon">

    <!-- Bootstrap core CSS -->
    <link href="{{ asset('lib/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <link href="{{ asset('lib/font-awesome/css/font-awesome.css') }}" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/zabuto_calendar.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('lib/gritter/css/jquery.gritter.css') }}"/>
    <!-- Custom styles for this template -->
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style-responsive.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/10.10.0/sweetalert2.css"
          integrity="sha512-i++eR2u4MtevO3tOPI55hNUccQVQ0+hf9cpevM2q/GmdM+UZMtzHn5pSxFmVuUK1kikm5qUiZB1ef6rWqLXb3Q=="
          crossorigin="anonymous"/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet"/>
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
    <style>
        hr {
            border-color: rgba(0, 0, 0, .07);
        }

        .font-weight-light {
            font-weight: 300 !important;
        }

        .swal2-popup {
            font-size: 1.6rem !important;
        }
    </style>


    <!-- =======================================================
      Template Name: Dashio
      Template URL: https://templatemag.com/dashio-bootstrap-admin-template/
      Author: TemplateMag.com
      License: https://templatemag.com/license/
    ======================================================= -->
    {% block stylesheets %}{% endblock %}
</head>
<body>
<section id="container">
    <!-- **********************************************************************************************************************************************************
        TOP BAR CONTENT & NOTIFICATIONS
        *********************************************************************************************************************************************************** -->
    <!--header start-->
    <header class="header black-bg">
        <div class="sidebar-toggle-box">
            <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
        </div>
        <!--logo start-->
        <a href="index.html" class="logo"><b>IMPER<span>IO</span></b></a>
        <!--logo end-->
        <div class="top-menu">
            <ul class="nav pull-right top-menu">
                <li><a class="logout" href="{{ path('app_logout') }}">Logout</a></li>
            </ul>
        </div>
    </header>
    <!--header end-->
    <!-- **********************************************************************************************************************************************************
        MAIN SIDEBAR MENU
        *********************************************************************************************************************************************************** -->
    <!--sidebar start-->
    <aside>
        <div id="sidebar" class="nav-collapse ">
            <!-- sidebar menu start-->
            <ul class="sidebar-menu" id="nav-accordion">
                <p class="centered"><a href="profile.html"><img src="{{ asset('img/ui-sam.jpg') }}" class="img-circle"
                                                                width="80"></a>
                </p>
                {% if app.user %}
                    <h5 class="centered">{{ app.user.username }}</h5>
                {% endif %}
                <li class="mt">
                    <a class="active" href="{{ path('dashboard') }}">
                        <i class="fa fa-dashboard"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fas fa-users-cog"></i>
                        <span>Usuários</span>
                    </a>
                    <ul class="sub">
                        <li><a href="{{ path('usuario_index') }}">Manter Usuário</a></li>
                        <li><a href="{{ path('tipo_usuario_index') }}">Manter Tipo de Usuário</a></li>
                        <li><a href="{{ path('funcionario_index') }}">Manter Funcionário</a></li>
                    </ul>
                </li>
            </ul>
            <!-- sidebar menu end-->
        </div>
    </aside>
</section>
<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-md-12">
                {% include 'alertas.html.twig' %}
                {% block body %}{% endblock %}
            </div>
        </div>
    </section>
</section>
{#<section class="wrapper">#}
{#    <div class="row">#}
<footer class="site-footer" style="margin-top: 200px">
    <div class="text-center">
        <p>
            &copy; Copyrights <strong>Imperio</strong>. Todos os direitos reservados
        </p>
        <div class="credits">
            <!--
              You are NOT allowed to delete the credit link to TemplateMag with free version.
              You can delete the credit link only if you bought the pro version.
              Buy the pro version with working PHP/AJAX contact form: https://templatemag.com/dashio-bootstrap-admin-template/
              Licensing information: https://templatemag.com/license/
            -->
            Desenvolvido por <a href="https://github.com/guilherme-lima-dev">Guilherme Lima</a> & <a href="https://www.linkedin.com/in/vin%C3%ADcius-ferreira-b67a88180/">Vinicius Ferreira</a>
        </div>
        {#        <a href="index.html#" class="go-top">#}
        {#            <i class="fa fa-angle-up"></i>#}
        {#        </a>#}
    </div>
</footer>
{#    </div>#}
{#</section>#}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>
{#<script src="{{ asset('lib/jquery/jquery-3.5.1.min.js') }}"></script>#}
<script src="{{ asset('lib/chart-master/Chart.js') }}"></script>
<script src="https://kit.fontawesome.com/1dbc7d90aa.js" crossorigin="anonymous"></script>
<script src="{{ asset('lib/bootstrap/js/bootstrap.min.js') }}"></script>
<script class="include" type="text/javascript" src="{{ asset('lib/jquery.dcjqaccordion.2.7.js') }}"></script>
<script src="{{ asset('lib/jquery.scrollTo.min.js') }}"></script>
<script src="{{ asset('lib/jquery.nicescroll.js') }}" type="text/javascript"></script>
<script src="{{ asset('lib/jquery.sparkline.js') }}"></script>
<!--common script for all pages-->
<script src="{{ asset('lib/common-scripts.js') }}"></script>
<script type="text/javascript" src="{{ asset('lib/gritter/js/jquery.gritter.js') }}"></script>
<script type="text/javascript" src="{{ asset('lib/gritter-conf.js') }}"></script>
<!--script for this page-->
<script src="{{ asset('lib/sparkline-chart.js') }}"></script>
<script src="{{ asset('lib/zabuto_calendar.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/10.10.0/sweetalert2.all.js"
        integrity="sha512-e7ZAMyNHTG4vWygAvkLIUNjAiuDvZBjIFvPVp48c138M6bLcP+WN7xJr9rxg61nfTjMvGuEzOLgnoYNnT3kzzQ=="
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $('#tabela-index').DataTable({
            language: {
                url: '//cdn.datatables.net/plug-ins/1.10.21/i18n/Portuguese-Brasil.json'
            },
            {% if app.request.get('_route') == 'usuario_index' %}
            columnDefs: [{
                targets: 3,
                orderable: false
            }],
            {% elseif app.request.get('_route') == 'tipo_usuario_index' %}
            columnDefs: [{
                targets: 2,
                orderable: false
            }],
            {% elseif app.request.get('_route') == 'funcionario_index' %}
            columnDefs: [{
                targets: 8,
                orderable: false
            }],
            {% endif %}
        });
        $('.select2').select2();
    });
</script>
</body>
</html>

templates/alertas.html.twig
{#{% for type, messages in app.session.flashbag.all() %}#}
{#    {% for message in messages %}#}
{#        <div class="alert alert-dismissible alert-{{ type }}" data-animate="true" style="">#}
{#            <button type="button" class="close" data-dismiss="alert" aria-label="Fechar"><span#}
{#                        aria-hidden="true">×</span></button>#}
{#            {{ message|raw }}#}
{#        </div>#}
{#    {% endfor %}#}
{#{% endfor %}#}

{#{% for type, messages in app.session.flashbag.all() %}#}
{#    {% for message in messages %}#}
{#        <div aria-live="polite" aria-atomic="true" style="position: relative; min-height: 200px;">#}
{#            <div class="toast" style="position: absolute; top: 0; right: 0;">#}
{#                <div class="toast-header">#}
{#                    <img src="..." class="rounded mr-2" alt="...">#}
{#                    <strong class="mr-auto">Bootstrap</strong>#}
{#                    <small>11 mins ago</small>#}
{#                    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">#}
{#                        <span aria-hidden="true">&times;</span>#}
{#                    </button>#}
{#                </div>#}
{#                <div class="toast-body">#}
{#                    {{ message|raw }}#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    {% endfor %}#}
{#{% endfor %}#}

<link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<script>
    $(document).ready(function () {
        {% for msg in app.session.flashBag.get('success') %}
        toastr.success("{{ msg|raw }}");
        {% endfor %}
        {% for msg in app.session.flashBag.get('info') %}
        toastr.info("{{ msg|raw }}");
        {% endfor %}
        {% for msg in app.session.flashBag.get('warning') %}
        toastr.warning("{{ msg|raw }}");
        {% endfor %}
        {% for msg in app.session.flashBag.get('error') %}
        toastr.error("{{ msg|raw }}");
        {% endfor %}

        toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": true,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        };
    });

</script>

templates/base.html.twig
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <title>{% block title %}Imperio{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ asset('lib/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <!--external css-->
    <link href="{{ asset('lib/font-awesome/css/font-awesome.css') }}" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/zabuto_calendar.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('lib/gritter/css/jquery.gritter.css') }}"/>
    <!-- Custom styles for this template -->
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style-responsive.css') }}" rel="stylesheet">
    <script src="{{ asset('lib/chart-master/Chart.js') }}"></script>

    {% block stylesheets %}{% endblock %}
</head>

<body>
<section id="container">
    <!-- **********************************************************************************************************************************************************
        TOP BAR CONTENT & NOTIFICATIONS
        *********************************************************************************************************************************************************** -->
    <!--header start-->
    <header class="header black-bg">
        <div class="sidebar-toggle-box">
            <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
        </div>
        <!--logo start-->
        <a href="{{ path('home') }}" class="logo"><b>IMPER<span>IO</span></b></a>
        <!--logo end-->

        <div class="top-menu">
            <ul class="nav pull-right top-menu">
                <li><a class="logout" href="{{ path('app_logout') }}">Logout</a></li>
            </ul>
        </div>
    </header>
    <!--header end-->
    <!-- **********************************************************************************************************************************************************
        MAIN SIDEBAR MENU
        *********************************************************************************************************************************************************** -->
    <!--sidebar start-->
    <aside>
        <div id="sidebar" class="nav-collapse ">
            <!-- sidebar menu start-->
            <ul class="sidebar-menu" id="nav-accordion">
                {#                <p class="centered"><a href="profile.html"><img src="img/ui-sam.jpg" class="img-circle" width="80"></a></p>#}
                {% if app.user %}
                    <h5 class="centered">{{ app.user.username }}</h5>
                {% endif %}
                <li class="mt">
                    <a class="" href="index.html">
                        <i class="fa fa-dashboard"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fas fa-users-cog"></i>
                        <span>Usuários</span>
                    </a>
                    <ul class="sub">
                        <li><a href="{{ path('usuario_index') }}">Manter Usuário</a></li>
                        <li><a href="{{ path('tipo_usuario_index') }}">Manter Tipo de Usuário</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-desktop"></i>
                        <span>UI Elements</span>
                    </a>
                    <ul class="sub">
                        <li><a href="general.html">General</a></li>
                        <li><a href="buttons.html">Buttons</a></li>
                        <li><a href="panels.html">Panels</a></li>
                        <li><a href="font_awesome.html">Font Awesome</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-cogs"></i>
                        <span>Components</span>
                    </a>
                    <ul class="sub">
                        <li><a href="grids.html">Grids</a></li>
                        <li><a href="calendar.html">Calendar</a></li>
                        <li><a href="gallery.html">Gallery</a></li>
                        <li><a href="todo_list.html">Todo List</a></li>
                        <li><a href="dropzone.html">Dropzone File Upload</a></li>
                        <li><a href="inline_editor.html">Inline Editor</a></li>
                        <li><a href="file_upload.html">Multiple File Upload</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-book"></i>
                        <span>Extra Pages</span>
                    </a>
                    <ul class="sub">
                        <li><a href="blank.html">Blank Page</a></li>
                        <li><a href="login.html">Login</a></li>
                        <li><a href="lock_screen.html">Lock Screen</a></li>
                        <li><a href="profile.html">Profile</a></li>
                        <li><a href="invoice.html">Invoice</a></li>
                        <li><a href="pricing_table.html">Pricing Table</a></li>
                        <li><a href="faq.html">FAQ</a></li>
                        <li><a href="404.html">404 Error</a></li>
                        <li><a href="500.html">500 Error</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-tasks"></i>
                        <span>Forms</span>
                    </a>
                    <ul class="sub">
                        <li><a href="form_component.html">Form Components</a></li>
                        <li><a href="advanced_form_components.html">Advanced Components</a></li>
                        <li><a href="form_validation.html">Form Validation</a></li>
                        <li><a href="contactform.html">Contact Form</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-th"></i>
                        <span>Data Tables</span>
                    </a>
                    <ul class="sub">
                        <li><a href="basic_table.html">Basic Table</a></li>
                        <li><a href="responsive_table.html">Responsive Table</a></li>
                        <li><a href="advanced_table.html">Advanced Table</a></li>
                    </ul>
                </li>
                <li>
                    <a href="inbox.html">
                        <i class="fa fa-envelope"></i>
                        <span>Mail </span>
                        <span class="label label-theme pull-right mail-info">2</span>
                    </a>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class=" fa fa-bar-chart-o"></i>
                        <span>Charts</span>
                    </a>
                    <ul class="sub">
                        <li><a href="morris.html">Morris</a></li>
                        <li><a href="chartjs.html">Chartjs</a></li>
                        <li><a href="flot_chart.html">Flot Charts</a></li>
                        <li><a href="xchart.html">xChart</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-comments-o"></i>
                        <span>Chat Room</span>
                    </a>
                    <ul class="sub">
                        <li><a href="lobby.html">Lobby</a></li>
                        <li><a href="chat_room.html"> Chat Room</a></li>
                    </ul>
                </li>
                <li>
                    <a href="google_maps.html">
                        <i class="fa fa-map-marker"></i>
                        <span>Google Maps </span>
                    </a>
                </li>
            </ul>
            <!-- sidebar menu end-->
        </div>
    </aside>
    <!--sidebar end-->
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
    <section id="main-content" style="height: 100vh;">
        <section class="wrapper">
            <div class="container">
                <div class="row">
                    {% block body %}{% endblock %}
                </div>
            </div>
            <!-- /row -->
        </section>
    </section>
    <!--main content end-->
    <!--footer start-->
    <footer class="site-footer">
        <div class="text-center">
            <p>
                &copy; Copyright <strong>Imperio</strong>. Todos os direitos reservados
            </p>
            <div class="credits">
                Desenvolvido por <a href="https://github.com/guilherme-lima-dev">Guilherme Lima</a>
            </div>
            {#            <a href="index.html#" class="go-top">#}
            {#                <i class="fa fa-angle-up"></i>#}
            {#            </a>#}
        </div>
    </footer>
    <!--footer end-->
</section>
<!-- js placed at the end of the document so the pages load faster -->
<script src="{{ asset('lib/jquery/jquery.min.js') }}"></script>

<script src="{{ asset('lib/bootstrap/js/bootstrap.min.js') }}"></script>
<script class="include" type="text/javascript" src="{{ asset('lib/jquery.dcjqaccordion.2.7.js') }}"></script>
<script src="{{ asset('lib/jquery.scrollTo.min.js') }}"></script>
<script src="{{ asset('lib/jquery.nicescroll.js') }}" type="text/javascript"></script>
<script src="{{ asset('lib/jquery.sparkline.js') }}"></script>
<!--common script for all pages-->
<script src="{{ asset('lib/common-scripts.js') }}"></script>
<script type="text/javascript" src="{{ asset('lib/gritter/js/jquery.gritter.js') }}"></script>
<script type="text/javascript" src="{{ asset('lib/gritter-conf.js') }}"></script>
<!--script for this page-->
<script src="{{ asset('lib/sparkline-chart.js') }}"></script>
<script src="{{ asset('lib/zabuto_calendar.js') }}"></script>
{#<script type="text/javascript">#}
{#    $(document).ready(function() {#}
{#        var unique_id = $.gritter.add({#}
{#            // (string | mandatory) the heading of the notification#}
{#            title: 'Welcome to Dashio!',#}
{#            // (string | mandatory) the text inside the notification#}
{#            text: 'Hover me to enable the Close Button. You can hide the left sidebar clicking on the button next to the logo.',#}
{#            // (string | optional) the image to display on the left#}
{#            image: 'img/ui-sam.jpg',#}
{#            // (bool | optional) if you want it to fade out on its own or just sit there#}
{#            sticky: false,#}
{#            // (int | optional) the time you want it to be alive for before fading out#}
{#            time: 8000,#}
{#            // (string | optional) the class name you want to apply to that specific message#}
{#            class_name: 'my-sticky-class'#}
{#        });#}

{#        return false;#}
{#    });#}
{#</script>#}
<script src="https://kit.fontawesome.com/1dbc7d90aa.js" crossorigin="anonymous"></script>
</body>

</html>